### ISSUE TITLE
Add FakeAssembly

### ISSUE THREAD

**Issue by onion108** [leachim6/hello-world#1128]
That's great! I even found Wenyan in there!
And I'm going to develop an useless assembly-like language called `FakeAssembly`.
I've done with output.
here is the hello world in FA:
```
@; By 27Onion
@; 
dliteral Hello
dchar ' '
dliteral World
```

**Comment by MrBrain295** [comment]
@onion108 this needs to be be but in pull request form, have the issue closed and have  link to the compiler.

**Comment by onion108** [comment]
OK. I'm gonna upload my compiler(actually, interpreter).
And... could you tell me how to upload a folder(directory) to the github repository please? thanks.

**Comment by MrBrain295** [comment]
@onion108 sorry I’m not understanding are you trying to upload the interpreter to one of your GitHub repository’s or this one? (I can give an explanation after this question is answered.)

**Comment by MrBrain295** [comment]
@onion108 this also should be renamed to a more explanatory title.

**Comment by onion108** [comment]
> @onion108 this should also be renamed to a more explanatory title.

Help me to  rename (lol because i'm not good at creating titles.)

And, I mean , I want to know how to upload a folder to the github repository. Any repository can be an example. I usually will add folders manually, but I found that it's not a good way when the structure of the project is too complex.
(Well, I'm not very good at English's grammar. So hope you can understand ;P)

**Comment by onion108** [comment]
> @onion108 this should also be renamed to a more explanatory title.

Help me to  rename (lol because i'm not good at creating titles.)

And, I mean , I want to know how to upload a folder to the github repository. Any repository can be an example. I usually will add folders manually, but I found that it's not a good way when the structure of the project is too complex.
(Well, I'm not very good at English's grammar. So hope you can understand ;P)

**Comment by onion108** [comment]
> @onion108 sorry I’m not understanding are you trying to upload the interpreter to one of your GitHub repository’s or this one? (I can give an explanation after this question is answered.)

Yeah, I'm going to create a repository for the interpreter but I want to know how to upload a folder first and then I'll create the repository and upload my interpreter(Written in `Swift`) to that repo.

**Comment by Richienb** [comment]
After creating a repository, [git clone](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/cloning-a-repository-from-github/cloning-a-repository) it locally, add the folder and then [git commit](https://github.com/git-guides/git-commit) and [git push](https://github.com/git-guides/git-push)
