### ISSUE TITLE
Conflicts of interest

### ISSUE THREAD

**Issue by Richienb** [leachim6/hello-world#1165]
In recent times, pull requests have been opened by the authors of the programming language that is being added. Should this conflict of interest be addressed in any way?

**Comment by MrBrain295** [comment]
I thought about this at one point; the only solution I could find would be put something int the readme stating that the creator of a language can’t add their own language.

**Comment by MrBrain295** [comment]
@Richienb should I revert prs that don’t follow this but have already been merged?

**Comment by Richienb** [comment]
Yes, but only for those which have been added in recent times. Some *may* have historical significance.
