### ISSUE TITLE
Put missing languages in wiki

### ISSUE THREAD

**Issue by calgary34** [leachim6/hello-world#1255]
Currently, the wiki section is empty so maybe the missing languages list could be put there. That way, if someone adds a language, it would be easier to edit the list.

**Comment by MrBrain295** [comment]
I like the idea. @Richienb what do you think?

**Comment by ThePeeps191** [comment]
yes, that would be good

**Comment by calgary34** [comment]
@MrBrain295 Can I go ahead and do it?

**Comment by Richienb** [comment]
Sure

**Comment by MrBrain295** [comment]
I think it’s settled then.
