### ISSUE TITLE
Kivy Also has Its Own Language, `.kv`

### ISSUE THREAD

**Issue by ThePeeps191** [leachim6/hello-world#1279]
We have the Kivy module in Python: `Kivy.py`, but Kivy also has its own language: Kivy with the `.kv` extension. Should we make any changes?

language: https://kivy.org/doc/stable/guide/lang.html

**Comment by MrBrain295** [comment]
Is the code any different?

**Comment by ThePeeps191** [comment]
yes

**Comment by ThePeeps191** [comment]
.kv is its own language, VERY different from python

**Comment by ThePeeps191** [comment]
it's called the "Kivy design language"

**Comment by ThePeeps191** [comment]
example:
```
Label:
        text: "Hello World"
```

(view https://www.techwithtim.net/tutorials/kivy-tutorial/the-kv-design-language-kv-file/)

**Comment by ThePeeps191** [comment]
and https://kivy.org/doc/stable/api-kivy.uix.label.html

**Comment by MrBrain295** [comment]
Then we should replace the Python lib with the language.

**Comment by calgary34** [comment]
The language is called Kv, not Kivy, as can be seen on the website.

**Comment by ThePeeps191** [comment]
as quoted:
```
The KV language, sometimes called kvlang or the kivy language, allows you to create your widget tree in a declarative way and to bind widget properties to each other or to callbacks in a natural manner.
```

**Comment by ThePeeps191** [comment]
its also called the kivy language

**Comment by calgary34** [comment]
@ThePeeps191 but the correct name is still KV

**Comment by calgary34** [comment]
Also, I think the Python one should be kept. Kivy (the Python module) and KV (the language) are different things.
