### ISSUE TITLE
HTML file is not the simplest

### ISSUE THREAD

**Issue by sastofficial** [leachim6/hello-world#1312]
[The HTML File](https://github.com/leachim6/hello-world/blob/master/h/HTML.html) looks like this
```<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Hello World</title>
</head>
<body>
  <h1>Hello World</h1>
</body>
</html>
```
When the simplest way to do it is
`<p>Hello World</p>`

**Comment by Richienb** [comment]
1. That's still not the simplest way.
2. The boilerplate is actually useful for people getting started.
