### ISSUE TITLE
Fix Malbolge file

### ISSUE THREAD

**Issue by Apollyon094** [leachim6/hello-world#1322]
First off, Malbolge programs use the .mb extension.
Second, this prints “Hello World” in half as many bytes.
`KD08YCM5XX42WlkzMlZ4LzRScyswTm8tJkprKSJGaH18QmN5Pyx2TnpdS1olb0c0VVVTMC9ALWVNYyg6Jzg= `
It’s in base64 since it keeps messing with Github’s markdown.

**Comment by MrBrain295** [comment]
@Apollyon094 if you want to fix Malbolge you should make a pull request.

**Comment by MrBrain295** [comment]
@Apollyon094 is the the code you intended to share (=<`#9]~6ZY32Vx/4Rs+0No-&Jk)"Fh}|Bcy?,vNz]KZ%oG4UUS0/@-eMc(:'8 ?
