### ISSUE TITLE
Coq seems to be missing

### ISSUE THREAD

**Issue by lquenti** [leachim6/hello-world#1350]
Coq is the most used theorem prover. I haven't found it in the repo.

I'd love to do a PR myself, but I haven't had the time to learn it yet and don't just wanna steal code. So up for grabs to anyone who wants!

**Comment by pierrbt** [comment]
You might use [this hello world program](https://github.com/coq-io/hello-world/blob/master/src/Main.v)

**Comment by pierrbt** [comment]
I created a [PR](https://github.com/leachim6/hello-world/pull/1423)
