### ISSUE TITLE
Many files not supported by NTFS

### ISSUE THREAD

**Issue by GoldenretriverYT** [leachim6/hello-world#1354]
The contributing.md states that files should not use characters blocked by windows, but similiar looking characters. However, files like https://github.com/leachim6/hello-world/blob/main/%23/*%3E%3C%3E didn't do that and therefore it is impossible to clone this repo to a Windows computer

**Comment by leachim6** [comment]
I noticed this myself, this will need to be reworked, thank you for pointing it out.

**Comment by 7koma95** [comment]
> The contributing.md states that files should not use characters blocked by windows, but similiar looking characters. However, files like https://github.com/leachim6/hello-world/blob/main/%23/*%3E%3C%3E didn't do that and therefore it is impossible to clone this repo to a Windows computer

**Comment by ahmedelsefir7** [comment]
لا يوجد كمبيوتر

**Comment by ahmedelsefir7** [comment]
موبايل ف الوقت الحالي

**Comment by GoldenretriverYT** [comment]
ah, sorry for the late reply but yep, its working now!
