### ISSUE TITLE
Apache Thrift seems to be missing

### ISSUE THREAD

**Issue by seanpm2001** [leachim6/hello-world#1377]
Apache Thrift seems to not be included in this repository. I checked both in `/a/` and `/t/`

I won't add it myself, it is up for grabs for whoever chooses to add it.

**Comment by MrBrain295** [comment]
If you want you can add it to the missing languages list on the wiki.

**Comment by seanpm2001** [comment]
I have updated the Wiki, but I will leave this issue open for now until the language is added, or if told otherwise.

**Comment by MrBrain295** [comment]
I don’t see a reason for having it on the wiki and having an issue for it so I’m closing it.
