### ISSUE TITLE
Don't you think that the hello-world is too simple?

### ISSUE THREAD

**Issue by chaosink** [leachim6/hello-world#158]
I think hello-world is too simple which can't show the main differences between languages. At least a loop and a conditional statement should be presented which are important parts in all languages.

Do you want add something new? Or create a new repository?

**Comment by javathunderman** [comment]
@leachim6 What do you think about an Android hello world? Or is that more akin to Java?

**Comment by racaljk** [comment]
but the original intention of the project is  to show HELLOWORLD

**Comment by JinweiClarkChao** [comment]
@racaljk You are right. But now we can do something more interesting than HelloWorld, like I have mentioned above, something like calculating from 1 to a billion in different languages and calculating the time they need.

**Comment by rdebath** [comment]
If you're looking for something more complex the traditional one is this:
http://rosettacode.org/wiki/Execute_Brain****

Either interpret directly or convert from BF to the language in question.

**Comment by JinweiClarkChao** [comment]
@rdebath It looks interesting.

**Comment by jannickfahlbusch** [comment]
All languages could calculate the first 100 prime numbers, or calculate the faculty of 100.

Definitively, it should be a task that shows the advantages (or disadvantages) of the language. 
Maybe everey language should get two tasks to solve.

**Comment by RhysBower** [comment]
One idea that I had was a string manipulation program that takes an array of names and your return them capitalized and reversed.  This would demonstrate variables, strings, arrays, looping and perhaps some other features of a language that would be nice to showcase.

**Comment by zenware** [comment]
[I just started something similar with the FizzBuzz problem](https://github.com/zenware/FizzBuzz), I'm not sure if it hits the right balance of triviality / language features used. But here it is anyways...

Maybe the [README](hello-world/README.md) in this project could be used to link to "x problem in every programming language" repositories.

I have faith that some day someone will find a reasonable thing to code in every language.

**Comment by rdebath** [comment]
:open_mouth:  _EVERY_ language? ... [there are **a lot** of languages](http://people.ku.edu/~nkinners/LangList/Extras/langlist.htm) and some of them have enough trouble with 'Hello World!'

**Comment by leachim6** [comment]
@rdebath, as I said before, it's a great idea, but it's outside the scope of this particular project.

**Comment by leachim6** [comment]
@zenware I'd love to lend a hand on that project, if you'd have me of course.

**Comment by zenware** [comment]
@leachim6 Sure, you probably know more than me anyways :P yours project is the inspiration after all...

**Comment by leachim6** [comment]
I really like the input I'm getting on this project, I now have a lot more free time to manage it thanks to the fact that I'm returning to school to finish my degree. If anyone has any other issues please let open one up and let me and the other contributors know! Thanks!

**Comment by Alhadis** [comment]
Being Australian, I always found "Hello, world" too American.

So I prefer settling for a proper Aussie "G'day, cunt" instead. =)

**Comment by GeorgeGibson** [comment]
@rdebath There is a language called Hello World. You cannot write a Hello World program in it.

**Comment by rdebath** [comment]
There are quite a few languages ([eg](http://esolangs.org/wiki/Deadfish) [eg](http://esolangs.org/wiki/Bitwise_Cyclic_Tag) [eg](http://esolangs.org/wiki/Unary)) that HW is impossible. If you translate the output or read the final memory to substitute for output some of them give you one but for some Turing complete languages the Hello World program is too large to fit in this universe.

I can't find your "Hello World" language, too much Google chaf, do you have a link ?

**Comment by GeorgeGibson** [comment]
@rdebath The HW compiler is still under development. It has an Esolangs article [here](https://esolangs.org/wiki/HelloWorld).

**Comment by leachim6** [comment]
Great feedback you guys, keep it comin'!

**Comment by Nikitaw99** [comment]
So um... There are 2 PRs awaiting to be read.
#258
#259

**Comment by petersobolev** [comment]
For assembler implementations simplicity of Hello World depends on platform (for example, see my 6809 (Vectrex) and TMS9900 (TI-99/4a) entries. So, it is useful project, keep it running.

**Comment by aloisdg** [comment]
By the way, to you know [Rosetta code](http://rosettacode.org/wiki/Rosetta_Code)?
