### ISSUE TITLE
Please move file

### ISSUE THREAD

**Issue by petersobolev** [leachim6/hello-world#263]
It seems that 
https://github.com/leachim6/hello-world/blob/master/assembler_tms9900_ti99_4a.asm should be in a/  as
https://github.com/leachim6/hello-world/blob/master/a/assembler_tms9900_ti99_4a.asm

(perhaps my mistake)

**Comment by leachim6** [comment]
Thanks for catching that peter! I have fixed this issue.
Thanks for your contribution
