### ISSUE TITLE
Lisp working?

### ISSUE THREAD

**Issue by trans** [leachim6/hello-world#271]
Not sure the lisp code actually does anything. -- It just defines a function to do something but never does it. I am not a Lisp expert but I imagine the function is unnecessary and the innards of it are all that is needed do the work.

**Comment by DrGodCarl** [comment]
The PR is newly opened for this issue:
https://github.com/leachim6/hello-world/pull/335

**Comment by RikerW** [comment]
It's been merged, somebody close this please?
