### ISSUE TITLE
HTML is not a programming language

### ISSUE THREAD

**Issue by sscarduzio** [leachim6/hello-world#274]
HTML is a markup language, you should remove HTML.

**Comment by afaqurk** [comment]
In that vain, neither is JSON, XML, SVG, etc. So either the project removes all of those as well or we simply accept that the project has gone beyond "programming languages".

I vote for the latter. I don't think removing those document markup formats adds any value besides some OCD satisfaction.

**Comment by rdebath** [comment]
Hello World is not a test of a language it's a test of the language environment, ie: this "hello world!" thing is supposed to give the usual results, if it doesn't the environment is still incomplete/broken. 

With that rule anything you can reasonably do an "environment test" for would be okay.

**Comment by deanturpin** [comment]
I vote for keeping everything too!

**Comment by Alhadis** [comment]
Should probably reword "programming language" to just "computer language", then. Because this is misleading:
<img width="341" alt="screen shot 2016-06-09 at 12 15 00 am" src="https://cloud.githubusercontent.com/assets/2346707/15897369/8d53fe24-2dd7-11e6-863b-41581c8c2f89.png">

**Comment by CubeFromSpace** [comment]
Idk, i saw all of this, very impressive by the way, but technically, HTML and other online stuff is still programming, as everything came from one guy's invention, binary. I think these versions of Hello World should stay. Yes, i am a random guy, and yes, i have no control over this.

**Comment by CubeFromSpace** [comment]
Yes, i do vote for keeping it all.

**Comment by Alhadis** [comment]
> but technically, **HTML and other online stuff is still programming**, as everything came from **one guy's** invention, **binary**

![good-story-laff](https://cloud.githubusercontent.com/assets/2346707/16754302/a25d2a9e-4834-11e6-851b-c5b5a409c728.png)

I love this repo.

**Comment by CubeFromSpace** [comment]
Edit: i looked it up on wikipedia, the guy who invented it was named Gottfried Leibniz. He was french.
Edit 2: I also saw on wikipedia that there are literally over 2,000 coding languages!! Sorry for the lack of capital letters.
Edit 3: time to Fork and Edit!! Yay!! Maybe tomorrow.

**Comment by Alhadis** [comment]
Warning: Poe's Law strictly enforced.

**Comment by Alhadis** [comment]
Tolkien invented binary, actually. The Binary programming language was based off his research of old Gaelic languages, and the language actually had 16 letters, not two (which is the origin of hexadecimal). However, the Americans decided to bastardise and grossly oversimplify the language, cutting it down to two. He died before the spec for the language could be completed, leaving his family and a fat Kiwi director to carry out his legacy.

What the actual fuck did I just write.

**Comment by leachim6** [comment]
Hey guys, I'm sorry I've been lax in processing pull requests, I plan on reviewing and merging all of the ones in my queue this weekend. Hack the planet!

**Comment by Qix-** [comment]
> technically, HTML and other online stuff is still programming, as everything came from one guy's invention, binary.

Nope, not even a little. HTML is a markup language - a data interchange format, if you will. Same with JSON. Same with SVG. Same with YAML. And so on.

They are not programming languages. They are used to convey and represent structured information. They do not (by themselves) run instructions or perform logic (even though, in some cases, they could be (ab)used to do so, such as with CSS).

---

On that note, I agree with @afaqurk 

> we simply accept that the project has gone beyond "programming languages" to a much broader scope

as well as @Alhadis 

> Should probably reword "programming language" to just "computer language"

since this is the first issue I looked for when I noticed these things.

**Comment by sscarduzio** [comment]
@leachim6 do you second what @Alhadis said about rewording "programming language" with "computer language"? This change will change a lot, for example I could stop washing my hands compulsively every time I think of this issue.

PS: JK, ::opens a new bag of pop corn::

**Comment by CubeFromSpace** [comment]
Now I feel stupid for saying that all those months ago XD

**Comment by sscarduzio** [comment]
Let's all promise we come back to this thread when we're drunk.

**Comment by Alhadis** [comment]
I don't drink, I just go 40-something hours without sleep and let endorphins do the rest.

**Comment by CubeFromSpace** [comment]
(I'm not old enough)

**Comment by leachim6** [comment]
Now I can never close this issue ! Thanks a lot you guys :P

**Comment by Alhadis** [comment]
I was hoping for a lock, but I found something quicker instead:

<img src="https://cloud.githubusercontent.com/assets/2346707/23940424/f0014b72-09b8-11e7-9e67-9788405baef3.png" alt="kek" />

**Comment by leachim6** [comment]
@Alhadis owch, my soul :/

**Comment by Alhadis** [comment]
I meant \*I\* was being retarded, ya silly muppet. :p

**Comment by thatHexa** [comment]
This thread... I can't even. 
When GitHub turns into reddit 😂

**Comment by leachim6** [comment]
This project was started for fun, I'd say mission accomplished!

**Comment by sscarduzio** [comment]
Yeah looks like reddit. But where are the cats?

**Comment by CubeFromSpace** [comment]
Cats are everywhere. Literally in almost every country. XD

**Comment by thatHexa** [comment]
Here we have octopuses. Even better.

**Comment by leachim6** [comment]
I'm not even mad, this is awesome

**Comment by CubeFromSpace** [comment]
This might as well be the best issue thread I've ever seen

**Comment by leachim6** [comment]
Phew, on that note, just committed the last pending pull request, my queue is now empty! Keep 'em coming folks!

**Comment by CubeFromSpace** [comment]
Not only that, this may be the best repository ever. I love how there's hilarious joke programming languages, like chicken and chef.

**Comment by thatHexa** [comment]
Soooo what's the sentence? Should we change the description to say "computer languages"?
The idea is great but I think we should find a better term..

**Comment by leachim6** [comment]
The current description says "computer languages" but if you can think of something better I'd love to hear it

**Comment by Potherca** [comment]
How about "Programming, markup and other computer languages"? That way you've got everything covered except natural/human languages.

**Comment by sscarduzio** [comment]
`<nitpicking>`
 "computer languages" doesn't mean anything. Programming languages are a subset of formal languages which happen to be particularly suited to perform computations. 

Now, there is no way Markdown, HTML, JSON, CSS are programming languages. 
`</nitpicking>`


`<paternalising>` 
If you want to include Markdown, HTML, JSON, CSS into this cauldron, the common denominator looks like "languages", or "formal languages" to a stretch.
`</paternalising>`

**Comment by Potherca** [comment]
Well... https://en.wikipedia.org/wiki/Computer_language seems to disagree with your nitpick.

It also neatly list all of the _other_ languages besides programming language that might show up, including stylesheet languages, query languages and, yes, markup languages.

**Comment by haqqer** [comment]
Hyper Text Markup Language (HTML) >>> Language <<< Bro

**Comment by azkarmoulana** [comment]
I vote for keeping everything

**Comment by sscarduzio** [comment]
@haqqer also french is a language, the major issue here is that it's not a **programming** language. 
🐸 BRO!

**Comment by iAhsanJaved** [comment]
I vote for keeping everything. 👍

**Comment by sscarduzio** [comment]
You could, but it would be incorrect

**Comment by ThexXTURBOXx** [comment]
![grafik](https://user-images.githubusercontent.com/12763829/54602992-7eac5c00-4a43-11e9-8737-dbf560396444.png)
Imo, that is correct now, as that is, what I learned at my university, too (HTML is a Markup Language, which is a subtype of Computer Languages)...
