### ISSUE TITLE
elm ?

### ISSUE THREAD

**Issue by stuaxo** [leachim6/hello-world#291]
Couldn't see elm-lang under E.

**Comment by RikerW** [comment]
[here you go](https://github.com/leachim6/hello-world/pull/384)

**Comment by stuaxo** [comment]
Awesome, hopefully will get merged soon :)

**Comment by leachim6** [comment]
https://github.com/leachim6/hello-world/commit/a0ca8f90f1da247138c279d5d71472f5f2031024
