### ISSUE TITLE
Whitespace example does not seem to be correct 

### ISSUE THREAD

**Issue by p4elkin** [leachim6/hello-world#339]
According to the wiki Whitespace lang syntax is supposed to support only tabs and spaces. However, the example provided looks more like some assembler code, is that right? <just pure curiosity>

**Comment by rdebath** [comment]
It works perfectly.

**Comment by phase** [comment]
Those are comments. They're telling you what the whitespace on each line is doing. Just highlight the code and you'll see it.

**Comment by p4elkin** [comment]
roger, thanks for clarification! Closed this one
