### ISSUE TITLE
Consistency

### ISSUE THREAD

**Issue by nloveladyallen** [leachim6/hello-world#344]
Some examples print `Hello World`, others `hello world`, others `Hello, world!`, etc. Go even prints `Hello, 世界` (which Google Translate tells me means "world"). I feel like the examples should be made more consistent by standardizing the exact message. I suggest `hello, world` because that is how it was printed in the earliest know [example](https://www.bell-labs.com/usr/dmr/www/btut.html) (scroll to section 7) of a hello world program, but whatever variation it is, there should be *some* consistency.

**Comment by Alhadis** [comment]
Feel free to submit a pull-request updating all 432 samples, then.

**Comment by leachim6** [comment]
Hello World is really just an easy to use boilerplate string. The entire point of the project is to get the programming language to print a string, what the string contains is not really that relevant.
