### ISSUE TITLE
Add a list of all the programming languages in your README.md

### ISSUE THREAD

**Issue by havanagrawal** [leachim6/hello-world#356]
From the point of view of a contributor, it's pretty tedious to check every directory and see if you've missed a language.

Instead, the README could maintain a list of all the languages already covered (which could in turn be links to the actual files). That way, I only have to do a Ctrl + F to check for a language.

Glad to make a PR for this, if you feel this is a valid need.

**Comment by sanspace** [comment]
This is indeed valid and useful for everyone not only the contributors. Please add it.

**Comment by leachim6** [comment]
I am currently working on implementing this.

Thanks for your input

**Comment by thatHexa** [comment]
I already took care of that :)
Take a look at [commit 510f849a54ccfddedc30106639765b7a4b7e618b](https://github.com/leachim6/hello-world/commit/510f849a54ccfddedc30106639765b7a4b7e618b) and [pull request 381](https://github.com/leachim6/hello-world/pull/381).

**Comment by leachim6** [comment]
We are working towards a resolution on this thanks to @thatHexa and their continuous improvements. I'm going to keep this issue open to document progress on this.

Thanks everyone

**Comment by thatHexa** [comment]
The listed languages are now links to the actual files. Now I'm bored again ;)
[Here's the commit.](https://github.com/leachim6/hello-world/pull/387/commits/292823b6948e82053188fe569c3a5343c2a0e605)

**Comment by leachim6** [comment]
Sorry for the delay, this update is awesome @thatHexa, clean script too I'm going to go ahead and close this one out now and keep moving on #317 and #316
