### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ElfQrin** [leachim6/hello-world#413]
Are the files released under any license (for example, GPL)? I couldn't find anything about it in README.md or CONTRIBUTING.md

**Comment by leachim6** [comment]
The implications of this question are interesting and I am currently looking into the best answer.
Thanks for bringing this to my attention

**Comment by leachim6** [comment]
Seems like the MIT license would be the most compatible with the licenses of all of the programming languages in a broad project like this

**Comment by Richienb** [comment]
They are released under MIT.
