### ISSUE TITLE
Smalltalk Naming Conventions Issue

### ISSUE THREAD

**Issue by jrg94** [leachim6/hello-world#454]
Hey, I was just poking around the repo, and I noticed that the following files exist:

- [smalltalk.sm](https://github.com/leachim6/hello-world/blob/master/s/smalltalk.sm)
- [hello.st](https://github.com/leachim6/hello-world/blob/master/s/hello.st)

The first file seems fine, at least according to [The Hello World Collection](https://helloworldcollection.github.io/#Smalltalk%C2%A0(simple)).

However, that second file doesn't appear to follow the naming conventions throughout the repo. That said, if someone wanted to rename it, I suggest `smalltalk-gnu` (that'll keep it under S). See the [GNU Smalltalk Repo](https://github.com/gnu-smalltalk/smalltalk).

Of course, I believe both scripts run under GNU Smalltalk ([tested here](https://www.jdoodle.com/execute-smalltalk-online)), so it may make sense just to remove the `hello.st` file.

**Comment by leachim6** [comment]
I am researching the best way forward on this. Great find, thanks for your contribution!

**Comment by Richienb** [comment]
Fixed in https://github.com/leachim6/hello-world/commit/dc75f068dc3674e378d5c27c707cd8e033e33c65#diff-561c42b5a19da8219cad15def2061935
