### ISSUE TITLE
please add in 易语言

### ISSUE THREAD

**Issue by lblblong** [leachim6/hello-world#465]
调试输出( “Hello World" )

**Comment by canpaisheji** [comment]
( “Hello World" )

**Comment by yxfzdnbc** [comment]
看了一圈没看到易语言,来这里果然看到了

**Comment by PhoenixZeng** [comment]
yes. a chinese program language.

**Comment by PhoenixZeng** [comment]
所以 我们为啥不直接提pr

**Comment by Beyarz** [comment]
What's the name of it?

**Comment by lblblong** [comment]
@Beyarz It is a Chinese programming language that is very friendly to Chinese people who are not good at English, such as me~

**Comment by lblblong** [comment]
@PhoenixZeng 突然想到没有 哈哈哈

**Comment by PhoenixZeng** [comment]
i think use the "易语言" as the name is better then named ELP in this peoject.  it should be put in the "y" dir.
But I think some people may not be able to display normally.

**Comment by Freakwill** [comment]
and “丙正正” which means c++ but is not c++

**Comment by Richienb** [comment]
Complete! https://github.com/leachim6/hello-world/blob/master/%23/%E6%98%93%E8%AF%AD%E8%A8%80.e

**Comment by Hisuifeng** [comment]
我看到易语言笑嘻了，原来是有甜菜！
