### ISSUE TITLE
GLSL and HLSL Missing

### ISSUE THREAD

**Issue by exellian** [leachim6/hello-world#571]
you could write a fragment shader that outputs hello world on screen!

**Comment by code2828** [comment]
Please open a pull request and close this issue, then add a comment in #733 which is a place just for missing languages.

**Comment by human-0** [comment]
What about SPIR-V?

**Comment by Richienb** [comment]
Moved to #790.

**Comment by MrBrain295** [comment]
@Richienb the “help needed” label needs removed
