### ISSUE TITLE
All links in the README in the a folder "a" are broken.

### ISSUE THREAD

**Issue by JaxBen98** [leachim6/hello-world#574]
An example, clicking Argh in the README in /a brings you to https://github.com/leachim6/hello-world/blob/master/a/a%5Cargh.agh, a 404.

**Comment by zmiles17** [comment]
I created a pull request for this issue. https://github.com/leachim6/hello-world/pull/588

**Comment by paulo9mv** [comment]
Aparently this README.md file was wrongly merged, since there is no reason for its existence on that particular folder. @leachim6 is it correct?

**Comment by paulo9mv** [comment]
Aparently this README.md file was wrongly merged. @leachim6 is it correct?

**Comment by Richienb** [comment]
Fixed!
