### ISSUE TITLE
Disable Wiki section

### ISSUE THREAD

**Issue by InvisibleRain** [leachim6/hello-world#680]
Link to CONTRIBUTE.MD also doesn't work

**Comment by yemfol** [comment]
SUGGESTED, (EASY-TO-LEARN) PROGRAMMING WEBSITES.

(1) https://www.w3schools.com/

(2) https://www.quackit.com/

(3) https://www.pluralsight.com/

Hi!

Listed above are some of the (easy-to-learn) programming language (reference websites) that I think everyone would find useful.

I will continue to update the list as soon as I come across such websites while browsing.

(https://github.com/yemfol/hello-world/wiki)

(https://github.com/yemfol/hello-world/projects)

**Comment by Richienb** [comment]
@leachim6 We should probably disable the wiki part then.

**Comment by Tyler887** [comment]
> @leachim6 We should probably disable the wiki part then.

In order to turn off the wiki, you need to do so in your repository settings.

**Comment by Tyler887** [comment]
> > > @leachim6 We should probably disable the wiki part then.
> > 
> > 
> > In order to turn off the wiki, you need to do so in your repository settings.
> 
> Only leachim6 has the ability to do that.

You can invite him to go to the settings tab and uncheck "Wikis". Boom. The wiki is deleted. To invite him, I recommend you to email mike@mikedonaghy.org.

**Comment by MrBrain295** [comment]
> > > > @leachim6 We should probably disable the wiki part then.
> > > 
> > > 
> > > In order to turn off the wiki, you need to do so in your repository settings.
> > 
> > 
> > Only leachim6 has the ability to do that.
> 
> You can invite him to go to the settings tab and uncheck "Wikis". Boom. The wiki is deleted. To invite him, I recommend you to email [mike@mikedonaghy.org](mailto:mike@mikedonaghy.org).

I did at one point.

**Comment by calgary34** [comment]
The missing languages list is now in the wiki.
