### ISSUE TITLE
Simplify SQL?

### ISSUE THREAD

**Issue by seyfahni** [leachim6/hello-world#707]
Why not simplify sql.sql to the following?
```sql
SELECT 'Hello world!';
```

(This works with at least MySQL, MariaDB and PostgreSQL.)

**Comment by Richienb** [comment]
We're trying to insert Hello World, not search for it.

**Comment by seyfahni** [comment]
Isn't a Hello World program supposed to print hello world?

The current code creates a table, inserts "Hello World!" and then selects it, thus printing the string.
My variant just selects it as a constannt, thus printing the string.

Though I have to agree that the current version better showcases the usual look of SQL code.

**Comment by Richienb** [comment]
@seyfahni Oh right. I thought `SELECT` only worked on pre-existing elements.
