### ISSUE TITLE
change "Programming languages" to "Computer languages" in README

### ISSUE THREAD

**Issue by piyushya012** [leachim6/hello-world#723]
Change "the list contains hello world in every programming language" to "the list contains hello world in every computer language"

The list also contains Scripting languages, Hardware disctiption languages, Markup languages and much more not just programming languages.

**Comment by piyushya012** [comment]
Now that's good. No more "HTML is a markup language not programmimg language". Simple solution to Stupid issues.
+1:

**Comment by simonewebdesign** [comment]
I bet the next issue is going to be something like "Languages are usually referred to as programming languages, not computer languages", this change will be reverted and the cycle will be complete.

**Comment by piyushya012** [comment]
No one will say that. All languages are categorised under Computer
Languages.

Its just that Programming languages is the frequently used term.
