### ISSUE TITLE
Trivial keyboard language

### ISSUE THREAD

**Issue by exellian** [leachim6/hello-world#729]
Language described in natural language:
Press Shift + H
Press e
Press l
Press l
Press o
Press Space
Press Shift + W
Press o
Press r
Press l
Press d

**Comment by srikar7777** [comment]
line 3 it's "print e" :)

**Comment by exellian** [comment]
> line 3 it's "print e" :)
yes sure i am german sry

**Comment by JohnWesleyK** [comment]
Wow, this is just amazing!!! XD

**Comment by MrBrain295** [comment]
@Richienb would this be spoken on programming?

**Comment by exellian** [comment]
I think because you as a human have to do every step and not the computer this is probably not considered as programming. Therefore I will close this issue

**Comment by MrBrain295** [comment]
@exellian yeah
