### ISSUE TITLE
Hello world —> Hello home?

### ISSUE THREAD

**Issue by idoo** [leachim6/hello-world#731]
Hello, I'm writing from 2020, currently, we have a problem called COVID-2019. The world health organization recommends staying at home as one of the recommended measures to prevent a pandemic of COVID-2019.

We, as developers could be part of the advocacy of this recommendation!

Let's have a `temporary current` branch `Hello Home` with changing `Hello world` text in snippets to `Hello home` involve and all developers around the world to contribute to this change to distribute the importance of this recommendation worldwide?

**Comment by rdebath** [comment]
Hello Sweden ... 
I'd say talking, like this, and using voip, [messages](https://www.who.int/news-room/feature-stories/detail/who-health-alert-brings-covid-19-facts-to-billions-via-whatsapp) and everything is more important than ever.

**Comment by Richienb** [comment]
Changing hundreds of examples to replace a word with another word is too big of a scale to be done. However, feel free to fork this repository and transform them yourselves.
