### ISSUE TITLE
Punch cards

### ISSUE THREAD

**Issue by texteng** [leachim6/hello-world#732]
I know this is stretching things to their limits, but I punchcards aren't on here. I found a punchcard emulator. http://tyleregeto.com/article/punch-card-emulator

I guess we could save it with an image extension (ex: punchcard.png) . It seems like there are several variations of punch card languages which I don't have time to learn at the moment. I figured I would post the idea here for future reference.

**Comment by PeterNau** [comment]
Nice idea, but punch cards are a program storage and input medium, not a language.

**Comment by MrBrain295** [comment]
@Richienb shouldn’t this be closed?

**Comment by MrBrain295** [comment]
@Richienb or do you consider it a language?

**Comment by Richienb** [comment]
> Nice idea, but punch cards are a program storage and input medium, not a language.

Yes
