### ISSUE TITLE
Missing languages

### ISSUE THREAD

**Issue by human-0** [leachim6/hello-world#733]
Seed, bytebytejump, unreadable and bitbitjump are missing from the list.

**Comment by Richienb** [comment]
We need a suitable Hello World example for Bytebytejump.

**Comment by code2828** [comment]
We also need a suitable Hello World for [Seed7](http://seed7.sourceforge.net/).

**Comment by code2828** [comment]
I have created a pull request . Please take a look at it (#744).

**Comment by code2828** [comment]
Found another one call "Dongbei" （东北）. See #748 .

**Comment by code2828** [comment]
I didn't see 8051 and E100 assembly in the README. Perhaps we should add them too? Note: I don't know how to write them, especially for E100, there is **barely any** documentation.

**Comment by code2828** [comment]
> We need a suitable Hello World example for Bytebytejump and unreadable.

I'm currently working on [unreadable programming language](https://esolangs.org/wiki/Unreadable).

**Comment by code2828** [comment]
Unreadable and ZIIM added! Here: #750

**Comment by Epictyphlosion** [comment]
ZScript would be a good addition, especially since ACS is already here

**Comment by Richienb** [comment]
Moved to #790.

**Comment by MrBrain295** [comment]
@Richienb the “help needed” label needs removed
