### ISSUE TITLE
Remove non-computer languages at list

### ISSUE THREAD

**Issue by realRyanZhang** [leachim6/hello-world#762]
That two languages sneaked into the list mark them as programming languages (文言 & 上海话).
Please remove them.

**Comment by Richienb** [comment]
@gzhangdev What do they mean in English?

**Comment by gzhangdev** [comment]
文言: Classical Chinese, also known as Literary Chinese is the language of the classic literature from the end of the Spring and Autumn period through to the end of the Han dynasty, a written form of Old Chinese

上海话: The Shanghainese language, also known as the Shanghai dialect.

References:
1. https://en.wikipedia.org/wiki/Classical_Chinese
2. https://en.wikipedia.org/wiki/Shanghainese

**Comment by scientificworld** [comment]
Wenyan & Shanghai ARE programming languages.
wenyan: [https://github.com/wenyan-lang/wenyan](url)
shanghai: [https://github.com/cabuliwallah/shanghai-from-dongbei](url)
