### ISSUE TITLE
Add `hacktoberfest` tag

### ISSUE THREAD

**Issue by Roshians** [leachim6/hello-world#817]

**Comment by Richienb** [comment]
I can't add tags to the repository.

**Comment by Richienb** [comment]
@leachim6 Can you add the `hacktoberfest` tag to this repository?

**Comment by Kunal-Sharma228** [comment]
I guess only the owner can do so. [Steps To Do So](https://hacktoberfest.digitalocean.com/hacktoberfest-update)

**Comment by Kunal-Sharma228** [comment]
Yeah, only repo owners or collaborators can add labels to issues unless it's a template

**Comment by leachim6** [comment]
Hey sorry all, I didn't realize you folks needed me to do these things and I had the email notifications switched off!
I'll be more wary of this in the future!

**Comment by Richienb** [comment]
Hasn't been added?

**Comment by leachim6** [comment]
I'm not really clear what adding this tag does, would adding "hacktoberfest" in Februrary 2022 sorta miss the boat? What am I missing here

**Comment by Richienb** [comment]
It's in anticipation for October

**Comment by Richienb** [comment]
Adding the tag is a thing we should just set and forget right now

**Comment by leachim6** [comment]
@Richienb thanks for the explanation, tag's been added!
