### ISSUE TITLE
Issue with the Bash program

### ISSUE THREAD

**Issue by jclc** [leachim6/hello-world#857]
The Bash script calls `echo`, which is part of GNU core utilities, not Bash itself. Calling an external program to demonstrate a language feature such as this is cheating.

**Comment by Richienb** [comment]
How do you think it should be fixed?

**Comment by jclc** [comment]
I don't believe Bash is capable of printing to standard output without the use of external programs, so it should be removed.

**Comment by jclc** [comment]
Same goes for `fish`, actually. `zsh` can stay since it has echo built in.

**Comment by jclc** [comment]
My bad. Apparently it is a builtin after all, despite `which` reporting otherwise. Only `zsh` correctly identified it as such.
