### ISSUE TITLE
Adding detail steps in how to contribute in "CONTRIBUTING.md"

### ISSUE THREAD

**Issue by sandeepksaini** [leachim6/hello-world#862]
If we can add detailed steps required on how to contribute to this repository in "CONTRIBUTING.md".
I would like to contribute and add a language to this repo.

**Comment by Richienb** [comment]
@sandeepksaini How should it be improved? https://github.com/leachim6/hello-world/blob/master/CONTRIBUTING.md

**Comment by sandeepksaini** [comment]
I am a beginner to git and still learning. I would like to add a "hello-world" file into this repo so if contributions file have some steps would have helped me to make a commit to this repo.

**Comment by Richienb** [comment]
The instructions state what the commits should have. Making a commit is universal.

**Comment by raiph** [comment]
Hi @Richienb,

In a comment above you linked to https://github.com/leachim6/hello-world/blob/master/CONTRIBUTING.md

It gives me a 404.

I found several references to the above, but I suspect they should be:

https://github.com/leachim6/hello-world/blob/master/contributing.md
