### ISSUE TITLE
Confusion with Hello World for GDscript

### ISSUE THREAD

**Issue by KripC2160** [leachim6/hello-world#881]
https://github.com/leachim6/hello-world/blob/664c1309c2a82c01f8affc4243c13d6bc74227aa/g/gdscript.gd#L4

I am a little confused with the GDscript version since the code for the GDscript sets the texts for the label entity when there is a `print()` function available which shows up in the debug console when you run the program. I feel like using `Node` instead of `Label` and `print("Hello world")` would suit more with GDscript

**Comment by Richienb** [comment]
PR welcome.

**Comment by Sd-Shivam** [comment]
> https://github.com/leachim6/hello-world/blob/664c1309c2a82c01f8affc4243c13d6bc74227aa/g/gdscript.gd#L4
> 
> I am a little confused with the GDscript version since the code for the GDscript sets the texts for the label entity when there is a `print()` function available which shows up in the debug console when you run the program. I feel like using `Node` instead of `Label` and `print("Hello world")` would suit more with GDscript
 
actually you are not assigning any area on window frame to display the text

use Richtextlabel to show the text on the display.
then try this script
extends RichTextLabel
func _ready():
   self.add_text("Hello World")

i hope it will be helpfull😊

**Comment by Richienb** [comment]
PR welcome

**Comment by KripC2160** [comment]
Oh, I meant by Debug Console since `print("hello world")` shows up in the debug console instead of the screen. If we are talking about displaying on-screen then Label and Rich Text Label would be suited.

**Comment by MrBrain295** [comment]
I asked this on godot contributers chat and they said the simplest way is to do “print(“Hello World”)”

**Comment by MrBrain295** [comment]
Also JavaScript prints it in the console instead of an alert so I don’t see a problem with gdscript printing in the console

**Comment by MrBrain295** [comment]
@Richienb the “help needed” label needs removed
