### ISSUE TITLE
suggestion for change in gdscript 

### ISSUE THREAD

**Issue by KripC2160** [leachim6/hello-world#882]
https://github.com/leachim6/hello-world/blob/664c1309c2a82c01f8affc4243c13d6bc74227aa/g/gdscript.gd#L4

I am a little confused with the GDscript version since the code for the GDscript sets the texts for the label entity when there is a `print()` function available which shows up in the debug console when you run the program. I feel like using `Node` instead of `Label` and `print("Hello world")` would suit more with GDscript

**Comment by Richienb** [comment]
Move to #881
