### ISSUE TITLE
Python in readme.md leads to a broken link (Page not found)

### ISSUE THREAD

**Issue by vmyu** [leachim6/hello-world#932]
**Steps to reproduce:**
1) Navigate to readme.md
2) Scroll down until you see Python
3) Click Python [(direct link)](https://github.com/leachim6/hello-world/blob/master/p/Python.py)

Expected result: Users should be directed to a hello world example.

Actual result: I am linked to the '404: This is not the webpage you are looking for' page

**Comment by vmyu** [comment]
I have submitted a pull request to fix this issue #931

**Comment by d1snin** [comment]
Same for `Android` and `Haskell`

**Comment by Richienb** [comment]
These have since been fixed.
