### ISSUE TITLE
Seprate Folder for Spoken Languages

### ISSUE THREAD

**Issue by MrBrain295** [leachim6/hello-world#952]
Separate Folder for Spoken Languages. Called "Spoken" maybe.

**Comment by Tyler887** [comment]
This issue is inactive and should be closed now!<br>Records: 0 comments, 0 users that made activity to this issue, 0 linked pulls, no assignees, 0% done

Also, can you describe your issue further? Be sure you are a Collaborator of this repo, so you can do this **yourself**!
<small>Notifying owner of repo with @leachim6.</small>

**Comment by arcturus140** [comment]
you mean "natural languages"

**Comment by MrBrain295** [comment]
what's the difference?

**Comment by arcturus140** [comment]
spoken language is just spoken, i.e. the sounds produced when talking. Natural languages are formally better defined, consisting of symbols and rules.

**Comment by 1MuhammadYahya** [comment]
yea that would certainly be better

**Comment by leachim6** [comment]
This feels out of scope, if people want to know how to literally say "hello world" in human spoken languages they can just use google translate? 🤷‍♂️that's my view

**Comment by arcturus140** [comment]
I think the project has already outgrown a little its original purpose, since some examples are more libraries than computer languages. I'm not sure where this project is going but this feature proposed here would decrease its usefulness to me.

**Comment by leachim6** [comment]
Yeah the project has grown way outside of what I started over 10 years ago here on Github.
I'd like to gets some more feedback from the contributors. I think spoken languages should be forked into a different project.

**Comment by MrBrain295** [comment]
@leachim6 would you like to make the fork or should I?

**Comment by MrBrain295** [comment]
@leachim6 I make a repo for spoken languages [here](https://github.com/MrBrain295/hello-world).

**Comment by leachim6** [comment]
Hey @MrBrain295 sorry I just got around to this, I've been really busy! I love the new repo, perhaps you could change it to something like hello-world-spoken or some such? What are your thoughts

**Comment by MrBrain295** [comment]
Done!

**Comment by MrBrain295** [comment]
Ok, I renamed it.

**Comment by abt8601** [comment]
Now that #1356 has been merged, I think this issue can be closed.
