### ISSUE TITLE
Remove Comments

### ISSUE THREAD

**Issue by MrBrain295** [leachim6/hello-world#996]
Should I make a pr that removes the comments in the code (unless it’s crediting the creator).

**Comment by Richienb** [comment]
Which files contain comments?

**Comment by MrBrain295** [comment]
Some assembly files

**Comment by MrBrain295** [comment]
Like this one [https://github.com/leachim6/hello-world/blob/master/a/Assembler%20FASM%20DOS.asm](https://github.com/leachim6/hello-world/blob/master/a/Assembler%20FASM%20DOS.asm)

**Comment by MrBrain295** [comment]
also a bunch don't even print "Hello World"

**Comment by Richienb** [comment]
Sure
